name: Tag and Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g., 0.1.0)"
        required: true

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Authenticate and Push Tag
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag -a v${{ github.event.inputs.version }} -m "Release v${{ github.event.inputs.version }}"
        git push origin v${{ github.event.inputs.version }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        body: |
          New release v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
